### PR TITLE
Update Installbuilder version

### PR DESCRIPTION
**Pull request by umbynos**
Update to the latest version of installbuilder, https://installbuilder.com/changelog.html

### CODE REVIEW

**Comment by umbynos** [comment]
@floydpink :eyes:

**Comment by floydpink** [comment]
@umbynos - I’ve given you write access to the repo - please feel free to merge this in yourself

**Comment by umbynos** [comment]
Thanks a lot @floydpink! How the push of the image on DockerHub works? It's a manual procedure?

**Comment by floydpink** [comment]
Yes, it is a manual process - you will need to build the latest container locally using docker CLI and then tag it as both the current version and latest and push them both to the Docker hub:

https://hub.docker.com/repository/docker/floydpink/ubuntu-install-builder

Do you have a docker hub login that I can try and add as a collaborator there? ⬆️

**Comment by umbynos** [comment]
https://hub.docker.com/u/umbobaldi

**Comment by floydpink** [comment]
Added you as a collaborator - please check Docker Hub to see if you can see this repo

**Comment by umbynos** [comment]
Updated on Docker Hub https://hub.docker.com/r/floydpink/ubuntu-install-builder/tags

**Comment by floydpink** [comment]
Thank you, @umbynos !

**Pull request merged**
