### PR TITLE
Update Installbuilder

### PR DESCRIPTION
**Pull request by umbynos**
update to the latest version of installbuilder, https://installbuilder.com/changelog.html

### CODE REVIEW

**Comment by floydpink** [comment]
Thank you, @umbynos !

**Comment by umbynos** [comment]
I noticed that you pushed only the `latest` tag on dockerhub.. It's possible to have also tag `21.3.0`?

**Comment by floydpink** [comment]
Will do in a few minutes, @umbynos

**Comment by floydpink** [comment]
@umbynos - done

**Pull request merged**
